{% set version = "0.8.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-philentropy
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/philentropy_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/philentropy/philentropy_{{ version }}.tar.gz
  sha256: 3aa6d4918168f4fe2c56ea3f26381b0ffc02f1d5b9b95e294bac1a34bf66be3e

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-kernsmooth
    - r-rcpp
    - r-poorman
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-kernsmooth
    - r-rcpp
    - r-poorman

test:
  commands:
    - $R -e "library('philentropy')"           # [not win]
    - "\"%R%\" -e \"library('philentropy')\""  # [win]

about:
  home: https://github.com/HajkD/philentropy
  license: GPL-2.0-only
  summary: Computes 46 optimized distance and similarity measures for comparing probability functions (Drost (2018) <doi:10.21105/joss.00765>). These comparisons between probability functions have their foundations in a broad range of scientific disciplines from mathematics to ecology. The aim of this package is to provide
    a core framework for clustering, classification, statistical inference, goodness-of-fit, non-parametric statistics, information theory, and machine learning tasks that are based on comparing univariate or multivariate probability functions.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: philentropy
# Type: Package
# Title: Similarity and Distance Quantification Between Probability Functions
# Version: 0.4.0
# Date: 2020-01-09
# Authors@R: person("Hajk-Georg", "Drost", role = c("aut", "cre"), email = "hajk-georg.drost@tuebingen.mpg.de", comment = c(ORCID = "http://orcid.org/0000-0002-1567-306X"))
# Maintainer: Hajk-Georg Drost <hajk-georg.drost@tuebingen.mpg.de>
# Description: Computes 46 optimized distance and similarity measures for comparing probability functions (Drost (2018) <doi:10.21105/joss.00765>). These comparisons between probability functions have their foundations in a broad range of scientific disciplines from mathematics to ecology. The aim of this package is to provide a core framework for clustering, classification, statistical inference, goodness-of-fit, non-parametric statistics, information theory, and machine learning tasks that are based on comparing univariate or multivariate probability functions.
# Depends: R (>= 3.1.2)
# Imports: Rcpp, dplyr, KernSmooth
# License: GPL-2
# LazyData: true
# LinkingTo: Rcpp
# URL: https://github.com/HajkD/philentropy
# Suggests: testthat, knitr
# VignetteBuilder: knitr
# BugReports: https://github.com/HajkD/philentropy/issues
# RoxygenNote: 7.0.2
# NeedsCompilation: yes
# Packaged: 2020-01-09 14:20:07 UTC; hdrost
# Author: Hajk-Georg Drost [aut, cre] (<https://orcid.org/0000-0002-1567-306X>)
# Repository: CRAN
# Date/Publication: 2020-01-10 00:00:03 UTC
